title: CS458 Manual
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://3-24.github.io/cs458-manual

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

callouts:
  warning:
    title: Warning
    color: red
  highlight:
    color: yellow
